version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  reviewers:
  - CaddyDz
  assignees:
  - CaddyDz
  labels:
  - dependencies
  - php
  versioning-strategy: increase
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  reviewers:
  - CaddyDz
  assignees:
  - CaddyDz
  labels:
  - dependencies
  - javascript
  versioning-strategy: increase
  allow:
  - dependency-type: direct
  - dependency-type: indirect