openapi: 3.0.0
info:
  title: 'Laravel auth documentation'
  description: 'The project is an api to authenticate a client app'
  contact:
    email: salim@sitando.com
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
servers:
  -
    url: 'http://kingboosting.test'
    description: 'Local env'
paths:
  /api/auth/login:
    post:
      tags:
        - Login
      summary: 'Generate a token for user'
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                password:
                  type: string
              type: object
              example:
                email: user@kingboosting.com
                password: password
      responses:
        200:
          description: OK
        403:
          description: Forbidden
  /api/getBoostersNames:
    get:
      tags:
        - Booster
      summary: 'Get usernames of all boosters'
      operationId: booster
      responses:
        200:
          description: Success
          content:
            application/json: []
  /api/orders:
    post:
      tags:
        - Order
      summary: 'Place a new order'
      operationId: order
      parameters:
        -
          name: service
          in: query
          required: true
          schema:
            type: string
        -
          name: tier
          in: query
          required: true
          schema:
            type: string
        -
          name: division
          in: query
          required: true
          schema:
            type: string
        -
          name: server
          in: query
          required: true
          schema:
            type: string
        -
          name: wins
          in: query
          required: true
          schema:
            type: string
        -
          name: queue
          in: query
          required: false
          schema:
            type: string
        -
          name: specific_champions
          in: query
          required: false
          schema:
            type: boolean
        -
          name: priority
          in: query
          required: false
          schema:
            type: boolean
        -
          name: streaming
          in: query
          required: false
          schema:
            type: boolean
        -
          name: price
          in: query
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Success
          content:
            application/json: []
        403:
          description: Forbidden
  /api/user:
    get:
      tags:
        - User
      summary: 'Fetch info of authenticated user'
      operationId: user
      responses:
        200:
          description: Success
          content:
            application/json: []
        401:
          description: Unauthenticated
components:
  securitySchemes:
    token:
      type: apiKey
      scheme: https
      description: 'Append ''Bearer '' to the token'
security:
  - []
