name: Check & fix styling

on:
  pull_request:
    branches: [develop]

jobs:
  style:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fix style
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --allow-risky=yes

      - name: Extract branch name
        id: extract_branch
        run: echo "branch=${GITHUB_HEAD_REF}" >> $GITHUB_ENV

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v2.3.0
        with:
          commit_message: Fix styling
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
